print(2+2.5)
print(5/2)
print(5%2)
print(round(4.56 , 3))
print(pow(2,2))
a = int(input("Enter 1st num = "))
b = int(input("Enter 2nd num = "))
power=((a+b)**2)
poewer2=((a-b)**3)
print("1st power valu = ",power)
print("2nd power valu = ",poewer2)